executable = /home/barmstrong/cluster/htcondor/cuda_wrapper.sh
arguments = /home/barmstrong/aframe_new/runs/run.sh
error = /fast/barmstrong/outputs/$(Cluster).err
output = /fast/barmstrong/outputs/$(Cluster).out
log = /fast/barmstrong/outputs/$(Cluster).log
request_memory = 1500G
request_cpus = 50
request_gpus = 8
requirements = (TARGET.CUDAGlobalMemoryMb > 30000) && regexp("B200", TARGET.CUDADeviceName)
MaxTime = 57600
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))
+BypassLXCfs="true"
environment = CONDOR_JOB_ID=$(Cluster)

queue
