executable = /home/barmstrong/cluster/htcondor/cuda_wrapper.sh
arguments = /home/barmstrong/aframe_new/runs/run.sh
error = /fast/barmstrong/outputs/$(Cluster).err
output = /fast/barmstrong/outputs/$(Cluster).out
log = /fast/barmstrong/outputs/$(Cluster).log
request_memory = 320000
request_cpus = 20
request_gpus = 4
requirements = (TARGET.CUDAGlobalMemoryMb > 60000) && regexp("A100", TARGET.CUDADeviceName)
MaxTime = 57600
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))
environment = CONDOR_JOB_ID=$(Cluster)

queue
